#!/bin/bash
TEXFILENAME="$1"
FILE="${TEXFILENAME%.*}"
rm -rf ${FILE}.out ${FILE}.aux ${FILE}.bbl ${FILE}.blg ${FILE}.log ${FILE}Notes.bib
xelatex ${FILE}.tex
xelatex ${FILE}.tex
rm -rf ${FILE}.out ${FILE}.aux ${FILE}.bbl ${FILE}.blg ${FILE}.log ${FILE}Notes.bib
